# sim_embed_files(<target> NAMESPACE <ns> FILES <file>...)
#
# Embeds binary files (fonts) in <target> as byte arrays generated at build time, so the binary
# runs from any directory, like the SPIR-V shaders (Shaders.cmake). A generated
# `<target>_assets.hpp` declares
#
#     std::span<const unsigned char> <ns>::embedded_file(std::string_view file_name);
#
# which returns the bytes of e.g. "FiraSans-Medium.ttf", or an empty span for unknown names.
# Regenerated when a file changes. No external tools: the conversion is a CMake script.
set(SIM_EMBED_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/EmbedFile.cmake")

function(sim_embed_files target)
  cmake_parse_arguments(ARG "" "NAMESPACE" "FILES" ${ARGN})
  if(NOT ARG_NAMESPACE OR NOT ARG_FILES)
    message(FATAL_ERROR "sim_embed_files: NAMESPACE and FILES are required")
  endif()

  set(gen_dir "${CMAKE_CURRENT_BINARY_DIR}/${target}_assets")
  set(sources "")
  set(decls "")
  set(lookups "")
  foreach(src IN LISTS ARG_FILES)
    get_filename_component(abs "${src}" ABSOLUTE)
    get_filename_component(file "${src}" NAME)
    string(MAKE_C_IDENTIFIER "asset_${file}" ident)
    set(out "${gen_dir}/${ident}.cpp")
    add_custom_command(
      OUTPUT "${out}"
      COMMAND "${CMAKE_COMMAND}" -DINPUT=${abs} -DOUTPUT=${out} -DSYMBOL=${ident}
              -DNAMESPACE=${ARG_NAMESPACE} -P "${SIM_EMBED_SCRIPT}"
      DEPENDS "${abs}" "${SIM_EMBED_SCRIPT}"
      COMMENT "Embedding ${file}"
      VERBATIM)
    list(APPEND sources "${out}")
    string(APPEND decls "extern const unsigned char ${ident}[];\nextern const std::size_t ${ident}_size;\n")
    string(APPEND lookups "    if (name == \"${file}\") return {${ident}, ${ident}_size};\n")
  endforeach()

  file(WRITE "${gen_dir}/${target}_assets.hpp.in"
"// Generated by sim_embed_files(); do not edit.
#pragma once

#include <span>
#include <string_view>

namespace ${ARG_NAMESPACE} {

// Bytes of an embedded file by name (\"FiraSans-Medium.ttf\"); empty if unknown.
std::span<const unsigned char> embedded_file(std::string_view name);

} // namespace ${ARG_NAMESPACE}
")
  file(WRITE "${gen_dir}/${target}_assets.cpp.in"
"// Generated by sim_embed_files(); do not edit.
#include \"${target}_assets.hpp\"

#include <cstddef>

namespace ${ARG_NAMESPACE} {

${decls}
std::span<const unsigned char> embedded_file(std::string_view name) {
${lookups}    return {};
}

} // namespace ${ARG_NAMESPACE}
")
  configure_file("${gen_dir}/${target}_assets.hpp.in" "${gen_dir}/${target}_assets.hpp" COPYONLY)
  configure_file("${gen_dir}/${target}_assets.cpp.in" "${gen_dir}/${target}_assets.cpp" COPYONLY)

  # The data arrays are plain generated code: compile them without our warning flags.
  add_library(${target}_assets OBJECT ${sources})
  target_sources(${target} PRIVATE $<TARGET_OBJECTS:${target}_assets> "${gen_dir}/${target}_assets.cpp")
  target_include_directories(${target} PRIVATE "${gen_dir}")
endfunction()
