# sim_add_spirv_shaders(<target> NAMESPACE <ns> SHADERS <file.vert|file.frag|file.comp>...)
#
# Compiles GLSL 450 shaders to SPIR-V at build time with glslangValidator and embeds the words
# in <target>, so the binary runs from any directory. glslang's --vn emits each module as a
# uint32_t array (correctly aligned SPIR-V words, no extra embedding tool); a generated
# `<target>_shaders.hpp` declares
#
#     std::span<const std::uint32_t> <ns>::embedded_shader(std::string_view file_name);
#
# which returns the module for e.g. "sprite.vert", or an empty span for unknown names. Shader
# #includes are tracked through glslang's depfile. Requires GLSLANG_VALIDATOR (Dependencies.cmake).
function(sim_add_spirv_shaders target)
  cmake_parse_arguments(ARG "" "NAMESPACE" "SHADERS" ${ARGN})
  if(NOT ARG_NAMESPACE OR NOT ARG_SHADERS)
    message(FATAL_ERROR "sim_add_spirv_shaders: NAMESPACE and SHADERS are required")
  endif()

  set(gen_dir "${CMAKE_CURRENT_BINARY_DIR}/${target}_spirv")
  set(headers "")
  set(includes "")
  set(lookups "")
  foreach(src IN LISTS ARG_SHADERS)
    get_filename_component(abs "${src}" ABSOLUTE)
    get_filename_component(file "${src}" NAME)
    string(MAKE_C_IDENTIFIER "spirv_${file}" ident)
    set(out "${gen_dir}/${ident}.h")
    add_custom_command(
      OUTPUT "${out}"
      COMMAND "${GLSLANG_VALIDATOR}" -V --target-env vulkan1.0 --quiet
              --vn "${ident}" --depfile "${out}.d" -o "${out}" "${abs}"
      DEPENDS "${abs}"
      DEPFILE "${out}.d"
      COMMENT "Compiling ${file} to SPIR-V"
      VERBATIM)
    list(APPEND headers "${out}")
    string(APPEND includes "#include \"${ident}.h\"\n")
    string(APPEND lookups "    if (name == \"${file}\") return ${ident};\n")
  endforeach()

  file(WRITE "${gen_dir}/${target}_shaders.hpp.in"
"// Generated by sim_add_spirv_shaders(); do not edit.
#pragma once

#include <cstdint>
#include <span>
#include <string_view>

namespace ${ARG_NAMESPACE} {

// SPIR-V words of an embedded shader by file name (\"sprite.vert\"); empty if unknown.
std::span<const std::uint32_t> embedded_shader(std::string_view name);

} // namespace ${ARG_NAMESPACE}
")
  file(WRITE "${gen_dir}/${target}_shaders.cpp.in"
"// Generated by sim_add_spirv_shaders(); do not edit.
#include \"${target}_shaders.hpp\"

#include <stdint.h> // glslang's --vn headers use the unqualified uint32_t

namespace {
${includes}} // namespace

namespace ${ARG_NAMESPACE} {

std::span<const std::uint32_t> embedded_shader(std::string_view name) {
${lookups}    return {};
}

} // namespace ${ARG_NAMESPACE}
")
  # configure_file only rewrites when the text changed, so unchanged shader lists don't rebuild.
  configure_file("${gen_dir}/${target}_shaders.hpp.in" "${gen_dir}/${target}_shaders.hpp" COPYONLY)
  configure_file("${gen_dir}/${target}_shaders.cpp.in" "${gen_dir}/${target}_shaders.cpp" COPYONLY)

  target_sources(${target} PRIVATE ${headers} "${gen_dir}/${target}_shaders.cpp")
  target_include_directories(${target} PRIVATE "${gen_dir}")
endfunction()
